import logo from '../assets/logo.svg';
import portrait01 from '../assets/portrait-1.png'
import tobi from '../assets/Tobi Oyebanji.webp'
import brand01 from '../assets/brand01.svg'
import brand02 from '../assets/brand02.svg'
import brand03 from '../assets/brand03.svg'
import brand04 from '../assets/brand04.png'
import mdlands from '../assets/mdlands.png'
import code from '../assets/code.svg'
import document from '../assets/document.svg'
import ico from '../assets/ico.svg'
import gericht from '../assets/gericht.png'
import gpt3 from '../assets/gpt3.png'
import ite from '../assets/ite.png'
import qrnaty from '../assets/qrnaty.png'
import makeknown from '../assets/makeknown.png'
import danpd from '../assets/danpd.png'
import adekunle from '../assets/adekunle.png'
import ogimage from '../assets/ogimage.png'

export default { logo, portrait01, tobi, brand01, brand02, brand03, brand04, mdlands, code, document, ico, gericht, gpt3, ite, qrnaty, makeknown, danpd, adekunle, ogimage };