export { default as Navbar } from './navbar/Navbar'
export { default as Headline } from './headline/Headline'
export { default as Testimonial } from './testimonial/Testimonial'
export { default as Footer } from './footer/Footer'
export { default as Skills } from './skills/Skills'